export const keys = {
  LOADING_PRODUCT: "LOADING_PRODUCT_DETAIL",
  LOADING_PRODUCT_LIST: "LOADING_PRODUCT_LIST",
  LOADING_PRODUCT_FEEDBACK: "LOADING_PRODUCT_FEEDBACK",

  ADD_TOAST: "ADD_TOAST",

  LOG_IN: "LOG_IN",
  LOG_OUT: "LOG_OUT",

  FINISH_LOADING_APP: "FINISH_LOADING_APP",

  LOADING_UPCOMING_BILL: "LOADING_UPCOMING_BILL",
  LOADING_COMPLETED_BILL: 'LOADING_COMPLETED_BILL',
  SEARCHING_BILL: "SEARCHING_BILL",
  SELECT_BILL: "SELECT_BILL",

  LOADING_ACCOUNTS: 'LOADING_ACCOUNTS'
};

export const getAction = (type, data) => ({ type, ...data });
