const keys = {

    USER_LOG_IN: 'USER_LOG_IN',
    USER_LOG_OUT: 'USER_LOG_OUT',

    SELECT_PRODUCT: 'SELECT_PRODUCT',

    PRODUCT_DATA_LOADING: 'PRODUCT_DATA_LOADING',
    PRODUCT_DATA_LOADED: 'PRODUCT_DATA_LOADED',
    PRODUCT_DATA_LOADING_FAILED: 'PRODUCT_DATA_LOADING_FAILED',
    PRODUCT_DATA_UPDATING_WATCH_LIST_STATE: 'PRODUCT_DATA_UPDATE_WATCH_LIST_STATE',
    PRODUCT_DATA_UPDATE_WATCH_LIST_STATE: 'PRODUCT_DATA_UPDATE_WATCH_LIST_STATE',


    FEEDBACK_LOADING: 'FEEDBACK_LOADING',
    FEEDBACK_LOADING_FAILED: 'FEEDBACK_LOADING_FAILED',
    FEEDBACK_LOADED: 'FEEDBACK_LOADED',

    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    REMOVE_ALL: 'REMOVE_ALL',

    SAVE_TO_BUFFER: 'SAVE_TO_BUFFER',

    WATCH_LIST_LOADING: 'WATCH_LIST_LOADING'

}

module.exports = keys