const keys = {

    USER_LOG_IN: 'USER_LOG_IN',
    USER_LOG_OUT: 'USER_LOG_OUT',

    SELECT_PRODUCT: 'SELECT_PRODUCT',
    PRODUCT_LIST_LOADING: 'PRODUCT_LIST_LOADING',
    PRODUCT_DETAIL_LOADING: 'PRODUCT_DETAIL_LOADING',
    WATCH_LIST_STATUS_FETCHING: 'WATCH_LIST_STATUS_FETCHING',

    FEEDBACK_LOADING: 'FEEDBACK_LOADING',
    GET_ANSWERS: 'GET_ANSWERS',

    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    REMOVE_ALL: 'REMOVE_ALL',

    SAVE_TO_BUFFER: 'SAVE_TO_BUFFER',

    WATCH_LIST_LOADING: 'WATCH_LIST_LOADING'

}

module.exports = keys