const keys = {

    USER_LOG_IN: 'USER_LOG_IN',
    USER_LOG_OUT: 'USER_LOG_OUT',

    SELECT_PRODUCT: 'SELECT_PRODUCT',
    PRODUCT_LIST_LOADING: 'PRODUCT_LIST_LOADING',
    PRODUCT_DETAIL_LOADING: 'PRODUCT_DETAIL_LOADING',

    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    REMOVE_ALL: 'REMOVE_ALL',

    SAVE_TO_BUFFER: 'SAVE_TO_BUFFER'

}

module.exports = keys