export const code = {
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  CONNECTION_ERROR: "CONNECTION_ERROR",
  DATA_NOT_FOUND: "DATA_NOT_FOUND"
};

