const keys = {

    USER_LOG_IN: 'USER_LOG_IN',
    USER_LOG_OUT: 'USER_LOG_OUT',

    NEWEST_PRODUCT_STATE_CHANGE: 'NEWEST_PRODUCT_STATE_CHANGE',
    CATEGORIES_STATE_CHANGE: 'CATEGORIES_STATE_CHANGE',
    PRODUCT_LIST_STATE_CHANGE: 'PRODUCT_LIST_STATE_CHANGE',
    PRODUCT_DETAIL_SET_ID: 'PRODUCT_DETAIL_SET_ID',
    PRODUCT_INFORMATION_STATE_CHANGE: 'PRODUCT_INFORMATION_STATE_CHANGE',
    PRODUCT_FEEDBACK_STATE_CHANGE: 'PRODUCT_FEEDBACK_STATE_CHANGE',
    PRODUCT_REVIEWS_PROCESSING_STATE_CHANGE: 'PRODUCT_REVIEWS_PROCESSING_STATE_CHANGE',

    SAVE_TO_BUFFER: 'SAVE_TO_BUFFER'

}

module.exports = keys