const keys = {

    USER_LOG_IN: 'USER_LOG_IN',
    USER_LOG_OUT: 'USER_LOG_OUT',

    SELECT_CATEGORY: 'SELECT_CATEGORY',
    SELECT_PRODUCT: 'SELECT_PRODUCT',
    PRODUCT_DATA_LOADING: 'PRODUCT_DATA_LOADING',
    PRODUCT_DATA_LOADED: 'PRODUCT_DATA_LOADED',
    PRODUCT_DATA_LOADING_FAILED: 'PRODUCT_DATA_LOADING_FAILED',
    PRODUCT_DATA_UPDATE_WATCH_LIST_STATE: 'PRODUCT_DATA_UPDATE_WATCH_LIST_STATE',
    REVIEW_PRODUCT: 'REVIEW_PRODUCT',


    FEEDBACK_LOADING: 'FEEDBACK_LOADING',
    FEEDBACK_LOADING_FAILED: 'FEEDBACK_LOADING_FAILED',
    FEEDBACK_LOADED: 'FEEDBACK_LOADED',

    NOTIFICATION_LOADING: 'NOTIFICATION_LOADING',
    NOTIFICATION_LOADING_FAILED: 'NOTIFICATION_LOADING_FAILED',
    NOTIFICATION_LOADED: 'NOTIFICATION_LOADED',
    SET_NOTIFICATION_STATUS: 'SET_NOTIFICATION_STATUS',
    APPEND_NOTIFICATION: 'APPEND_NOTIFICATION',
    CONNECTION_STATUS_SETTING: 'CONNECTION_STATUS_SETTING',

    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    REMOVE_ALL: 'REMOVE_ALL',

    PROMOTION_LOADING: 'PROMOTION_LOADING',
    PROMOTION_LOADING_FAILED: 'PROMOTION_LOADING_FAILED',
    PROMOTION_LOADED: 'PROMOTION_LOADED',

    SAVE_TO_BUFFER: 'SAVE_TO_BUFFER',

    WATCH_LIST_LOADING: 'WATCH_LIST_LOADING'

}

function getAction(type, data) {
    return { type, ...data }
}

module.exports = {
    ...keys,
    getAction
}